apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-api
  template:
    metadata:
      labels:
        app: mlops-api
    spec:
      containers:
        - name: mlops-api
          image: gcr.io/digital-gearbox-476106-a0/mlops-api:latest
          ports:
            - containerPort: 5000